In [22]:
import requests
import pandas as pd
import os
import openpyxl
import numpy as np
import itertools
import re

In [35]:
concurso = [2620, 2621]

for resultado in concurso:
    api = f'https://loteriascaixa-api.herokuapp.com/api/megasena/{resultado}'
    response = requests.get(api)
    if response.status_code == 200:
        print ('requisição: OK!')
        dados = response.json()
        print('transformando no formato json')
    else:
        print ('Erro!')
    

    print(dados)

requisição: OK!
transformando no formato json
{'loteria': 'megasena', 'concurso': 2620, 'data': '12/08/2023', 'local': 'ESPAÇO DA SORTE em SÃO PAULO, SP', 'dezenasOrdemSorteio': ['26', '21', '13', '04', '06', '28'], 'dezenas': ['04', '06', '13', '21', '26', '28'], 'trevos': [], 'timeCoracao': None, 'mesSorte': None, 'premiacoes': [{'descricao': '6 acertos', 'faixa': 1, 'ganhadores': 4, 'valorPremio': 29058128.28}, {'descricao': '5 acertos', 'faixa': 2, 'ganhadores': 404, 'valorPremio': 23042.04}, {'descricao': '4 acertos', 'faixa': 3, 'ganhadores': 21667, 'valorPremio': 613.76}], 'estadosPremiados': [], 'observacao': '', 'acumulou': False, 'proximoConcurso': 2621, 'dataProximoConcurso': '16/08/2023', 'localGanhadores': [{'ganhadores': 1, 'municipio': 'CANAL ELETRONICO', 'nomeFatansiaUL': '', 'serie': '', 'posicao': 1, 'uf': '--'}, {'ganhadores': 1, 'municipio': 'UBERABA', 'nomeFatansiaUL': '', 'serie': '', 'posicao': 1, 'uf': 'MG'}, {'ganhadores': 2, 'municipio': 'SINOP', 'nomeFatansia

In [ ]:
from datetime import datetime

timestamp = datetime.now().strftime('%Y%m%d_%H%M%S')

file = '/workspaces/projeto_ing/apis/setting/Mega-Sena(3).xlsx'
file_save = '/workspaces/projeto_ing/apis/app/tmp/'
wb = openpyxl.load_workbook(filename=file)

name = f'resultado_mega_{timestamp}.txt'
caminho = file_save + name
print(caminho)

dict_dfs = {}


for sheet in wb.sheetnames:
    sheet_data = []
    for row in wb[sheet].iter_rows(values_only=True):
        sheet_data.append(row)
    
    df = pd.DataFrame(sheet_data[1:], columns=sheet_data[0])
    print(df)
    df.to_csv(caminho, sep=';', index=False)
    print(f'arquivo salvo: {caminho}')
    
    

/workspaces/projeto_ing/apis/app/tmp/resultado_mega_20241230_150630.txt
      Concurso Data do Sorteio  Bola1  Bola2  Bola3  Bola4  Bola5  Bola6  \
0            1      11/03/1996      4      5     30     33     41     52   
1            2      18/03/1996      9     37     39     41     43     49   
2            3      25/03/1996     10     11     29     30     36     47   
3            4      01/04/1996      1      5      6     27     42     59   
4            5      08/04/1996      1      2      6     16     19     46   
...        ...             ...    ...    ...    ...    ...    ...    ...   
2804      2805      07/12/2024      1      6     24     47     55     58   
2805      2806      10/12/2024      5     11     13     33     45     46   
2806      2807      12/12/2024      8     25     49     52     55     56   
2807      2808      14/12/2024     10     24     33     35     41     46   
2808      2809      17/12/2024      2      4     15     28     34     39   

      Ganhadore

In [44]:
load = '/workspaces/projeto_ing/apis/app/tmp/resultado_mega_20241230_150630.txt'

df = pd.read_csv(load, sep=';', index_col=False)
# display(df)
df_conc = df['Concurso']
print(df_conc)

valores_filtrados = [valor for valor in df_conc.values.flatten() if 1 <= valor <= 60]
print(valores_filtrados)
valores_array = np.array(valores_filtrados)
valores_mais_frequentes, contagens = np.unique(valores_array, return_counts=True)

# df_result = df_conc.apply(pd.to_numeric, errors= 'coerse')
# display(df_result)

indices_mais_frequentes = np.argsort(-contagens)[:24]
valores_mais_frequentes = valores_mais_frequentes[indices_mais_frequentes]
# print(f'valores mais frequentes: {valores_mais_frequentes}')
print(indices_mais_frequentes)

valores_mais_frequentes = np.random.random(1)
print(valores_mais_frequentes)

valores_mais_frequentes = np.floor(60*np.random.random((10,6))) 
print(valores_mais_frequentes)

0          1
1          2
2          3
3          4
4          5
        ... 
2804    2805
2805    2806
2806    2807
2807    2808
2808    2809
Name: Concurso, Length: 2809, dtype: int64
[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60]
[ 0 32 33 34 35 36 37 38 39 40 41 42 43 31 44 46 47 48 49 50 51 52 53 54]
[0.44028952]
[[23.  3. 16. 13. 59. 28.]
 [35.  8. 23. 20. 54. 15.]
 [10. 21. 24. 58. 50.  4.]
 [18. 24. 43. 19.  7.  9.]
 [28. 21. 43. 24. 58. 27.]
 [37. 30.  3. 28. 38. 25.]
 [34. 54. 36. 34. 50. 57.]
 [17. 30. 22.  9.  0. 19.]
 [18.  2. 18. 14. 10. 42.]
 [51. 52. 24. 31. 44. 35.]]


In [20]:
def calcular_maior_numero_jogos(numeros_disponiveis, tamanho_jogo, quantidade_jogos):
    combinacoes = list(itertools.combinations(numeros_disponiveis, tamanho_jogo))
    
    jogos = []

    for combinacao in combinacoes:
        if len(jogos) >= quantidade_jogos:
            break
        if all(set(combinacao).isdisjoint(jogo) for jogo in jogos):
            jogos.append(combinacao)
    
    return jogos
print('Função carregada!')

Função carregada!


In [31]:
numeros_disponiveis = re.findall(r'\d+', str(valores_mais_frequentes))
numeros_disponiveis = [int(numero) for numero in numeros_disponiveis]

tamanho_jogo = 6
quantidade_jogos = 4
jogos = calcular_maior_numero_jogos(numeros_disponiveis, tamanho_jogo, quantidade_jogos)
display(jogos)

[(1, 33, 34, 35, 36, 37),
 (38, 39, 40, 41, 42, 43),
 (44, 32, 45, 47, 48, 49),
 (50, 51, 52, 53, 54, 55)]

api = 'https://loteriascaixa-api.herokuapp.com/api/'

response = requests.get(api)
print(response)
dados = response.json()
print(dados)

In [17]:
concurso = [2620, 2621]
print(concurso)

[2620, 2621]


In [ ]:
concurso = [2620, 2621]

for resultado in concurso:
    api = f'https://loteriascaixa-api.herokuapp.com/api/megasena/{resultado}'
    response = requests.get(api)
    if response.status_code == 200:
        print ('requisição: OK!')
        dados = response.json()
        print('transformando no formato json')
    else:
        print ('Erro!')
    
    print(dados)
    

requisição: OK!
transformando no formato json
{'loteria': 'megasena', 'concurso': 2620, 'data': '12/08/2023', 'local': 'ESPAÇO DA SORTE em SÃO PAULO, SP', 'dezenasOrdemSorteio': ['26', '21', '13', '04', '06', '28'], 'dezenas': ['04', '06', '13', '21', '26', '28'], 'trevos': [], 'timeCoracao': None, 'mesSorte': None, 'premiacoes': [{'descricao': '6 acertos', 'faixa': 1, 'ganhadores': 4, 'valorPremio': 29058128.28}, {'descricao': '5 acertos', 'faixa': 2, 'ganhadores': 404, 'valorPremio': 23042.04}, {'descricao': '4 acertos', 'faixa': 3, 'ganhadores': 21667, 'valorPremio': 613.76}], 'estadosPremiados': [], 'observacao': '', 'acumulou': False, 'proximoConcurso': 2621, 'dataProximoConcurso': '16/08/2023', 'localGanhadores': [{'ganhadores': 1, 'municipio': 'CANAL ELETRONICO', 'nomeFatansiaUL': '', 'serie': '', 'posicao': 1, 'uf': '--'}, {'ganhadores': 1, 'municipio': 'UBERABA', 'nomeFatansiaUL': '', 'serie': '', 'posicao': 1, 'uf': 'MG'}, {'ganhadores': 2, 'municipio': 'SINOP', 'nomeFatansia

In [27]:
concurso = [2620]
api = f'https://loteriascaixa-api.herokuapp.com/api/megasena/{concurso}'

response = requests.get(api)
print(response)
dados = response.json()
print(dados)

<Response [400]>
{'status': 400, 'error': 'Bad Request', 'message': 'Failed to convert value of type \'java.lang.String\' to required type \'java.lang.Integer\'; nested exception is java.lang.NumberFormatException: For input string: "[2620]"', 'timestamp': 1735570015187, 'path': '/api/megasena/%5B2620%5D'}


In [29]:
for resultado in concurso:
    print(int(resultado))

2620
